using System.Collections.Generic;
using UnityEngine;

namespace BakaBakeBakery.Core
{
    public enum BakerySound
    {
        UiTap,
        Knead,
        OvenDoor,
        BakeReady,
        ShopBell,
        Coin,
        Discovery,
        DayBell
    }

    /// <summary>
    /// The bakery's ears. Three voices only: one for the little wooden noises the player causes,
    /// one for the room humming under everything, and one for the music box.
    ///
    /// It builds itself after the first scene loads, so no scene has to carry a prefab, and it
    /// survives scene changes rather than restarting the room tone at every door.
    /// Clips are generated by <c>Tools/generate_audio.py</c>.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class BakeryAudio : MonoBehaviour
    {
        private const float OneShotVolume = 0.62f;
        private const float AmbienceVolume = 0.2f;
        private const float MusicVolume = 0.2f;

        private static BakeryAudio instance;

        private readonly Dictionary<BakerySound, AudioClip> clips = new();
        private AudioSource oneShotSource;
        private AudioSource ambienceSource;
        private AudioSource musicSource;
        private float ambienceTarget = AmbienceVolume;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void Bootstrap()
        {
            if (instance != null)
            {
                return;
            }

            var host = new GameObject("Bakery Audio");
            DontDestroyOnLoad(host);
            host.AddComponent<BakeryAudio>();
        }

        private void Awake()
        {
            if (instance != null && instance != this)
            {
                Destroy(gameObject);
                return;
            }

            instance = this;
            oneShotSource = CreateSource("One Shots", false, OneShotVolume);
            ambienceSource = CreateSource("Room Tone", true, 0f);
            musicSource = CreateSource("Music Box", true, MusicVolume);

            foreach (BakerySound sound in System.Enum.GetValues(typeof(BakerySound)))
            {
                var clip = Resources.Load<AudioClip>($"Audio/{FileName(sound)}");
                if (clip != null)
                {
                    clips[sound] = clip;
                }
            }

            StartLoop(ambienceSource, "Audio/room_tone");
            StartLoop(musicSource, "Audio/music_home");
        }

        private void Update()
        {
            if (ambienceSource == null)
            {
                return;
            }

            // The room breathes in when the shutter goes up rather than snapping to volume.
            ambienceSource.volume = Mathf.MoveTowards(
                ambienceSource.volume,
                ambienceTarget,
                Time.unscaledDeltaTime * 0.35f);
        }

        private void OnDestroy()
        {
            if (instance == this)
            {
                instance = null;
            }
        }

        /// <summary>A small pitch wobble keeps repeated sounds from turning into a machine.</summary>
        public static void Play(BakerySound sound, float volumeScale = 1f)
        {
            if (instance == null || instance.oneShotSource == null)
            {
                return;
            }

            if (!instance.clips.TryGetValue(sound, out var clip) || clip == null)
            {
                return;
            }

            instance.oneShotSource.pitch = Random.Range(0.96f, 1.05f);
            instance.oneShotSource.PlayOneShot(clip, Mathf.Clamp01(volumeScale) * OneShotVolume);
        }

        /// <summary>Lifts the room tone while the bakery is trading and lets it settle when it rests.</summary>
        public static void SetShiftOpen(bool open)
        {
            if (instance != null)
            {
                instance.ambienceTarget = open ? AmbienceVolume : AmbienceVolume * 0.35f;
            }
        }

        private AudioSource CreateSource(string sourceName, bool loop, float volume)
        {
            var host = new GameObject(sourceName);
            host.transform.SetParent(transform, false);
            var source = host.AddComponent<AudioSource>();
            source.playOnAwake = false;
            source.loop = loop;
            source.volume = volume;
            source.spatialBlend = 0f;
            source.ignoreListenerPause = true;
            return source;
        }

        private static void StartLoop(AudioSource source, string resourcePath)
        {
            var clip = Resources.Load<AudioClip>(resourcePath);
            if (source == null || clip == null)
            {
                return;
            }

            source.clip = clip;
            source.Play();
        }

        private static string FileName(BakerySound sound)
        {
            return sound switch
            {
                BakerySound.UiTap => "ui_tap",
                BakerySound.Knead => "knead",
                BakerySound.OvenDoor => "oven_door",
                BakerySound.BakeReady => "bake_ready",
                BakerySound.ShopBell => "shop_bell",
                BakerySound.Coin => "coin",
                BakerySound.Discovery => "discovery",
                BakerySound.DayBell => "day_bell",
                _ => string.Empty
            };
        }
    }
}
